-- SQLite
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Shawshank Redemption', 1994, 'R', 142, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES( 'The Godfather', 1972, 'R', 175, 'Crime');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Godfather: Part II', 1974, 'R', 202, 'Crime');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Dark Knight', 2008, 'PG-13', 152, 'Action');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( '12 Angry Men', 1957, 'Not Rated', 96, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Schindlers List', 1993, 'R', 195, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Lord of the Rings: The Return of the King', 2003, 'PG-13', 201, 'Fantasy');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Pulp Fiction', 1994, 'R', 154, 'Crime');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Good, the Bad and the Ugly', 1966, 'Not Rated', 161, 'Western');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Fight Club', 1999, 'R', 139, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Forrest Gump', 1994, 'PG-13', 142, 'Comedy');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Inception', 2010, 'PG-13', 148, 'Sci-Fi');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Lord of the Rings: The Fellowship of the Ring', 2001, 'PG-13', 178, 'Fantasy');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'One Flew Over the Cuckoos Nest', 1975, 'R', 133, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Goodfellas', 1990, 'R', 146, 'Crime');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Matrix', 1999, 'R', 136, 'Sci-Fi');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Seven Samurai', 1954, 'Not Rated', 207, 'Adventure');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Star Wars: Episode V - The Empire Strikes Back', 1980, 'PG', 204, 'Fantasy');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Silence of the Lambs', 1991, 'R', 118, 'Thriller');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Its a Wonderful Life', 1946, 'PG', 130, 'Family');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Life is Beautiful', 1997, 'PG-13', 116, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Saving Private Ryan', 1998, 'R', 169, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Léon: The Professional', 1994, 'R', 110, 'Thriller');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Usual Suspects', 1995, 'R', 106, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'American History X', 1998, 'R', 119, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Interstellar', 2014, 'PG-13', 169, 'Sci-Fi');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Prestige', 2006, 'PG-13', 130, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Departed', 2006, 'R', 151, 'Thriller');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Whiplash', 2014, 'R', 106, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Avengers', 2012, 'PG-13', 143, 'Action');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Intouchables', 2011, 'R', 112, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Social Network', 2010, 'PG-13', 120, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Revenant', 2015, 'R', 156, 'Adventure');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Terminator', 1984, 'R', 107, 'Sci-Fi');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'Jurassic Park', 1993, 'PG-13', 127, 'Adventure');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Truman Show', 1998, 'PG', 103, 'Drama');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Grand Budapest Hotel', 2014, 'R', 100, 'Adventure');
INSERT INTO Films (title, yearReleased, rating, duration, genre) VALUES ( 'The Prestige', 2006, 'PG-13', 130, 'Drama');